### ISSUE TITLE
Pip still installs old version

### ISSUE THREAD

**Issue by cmrd-senya** [bin3xish477/cloudfront-signed-cookies#3]
You've made some changes to the API of Signer init method.

The readme file uses `private_key` parameter. However the version I installed from pip is older and I got the error:
```
senya@senya-Latitude-5511:/tmp$ python3.8 ~/cookies.py 
Traceback (most recent call last):
  File "/home/senya/cookies.py", line 31, in <module>
    main()
  File "/home/senya/cookies.py", line 9, in main
    signer: Signer = Signer(
TypeError: __init__() got an unexpected keyword argument 'private_key'
```

I worked that around by changing `private_key` to `priv_key_file` in the example I run. But it'd be nice if the published version corresponded to the readme file.

**Comment by bin3xish477** [comment]
New release published: https://pypi.org/project/cloudfront-signed-cookies/1.2/
